// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title R+4 Groth16 Verifier (BN254)
 * @notice On-chain verifier for R+4 zero-knowledge proofs.
 *         Sketch contract — production version is auto-generated by snarkjs from the trusted setup.
 *
 * @dev Per spec §9.2, verifies a Groth16 proof over the BN254 curve using
 *      Ethereum's bn256 precompile (Base mainnet supports the same).
 *      Cost: approximately 250,000 gas per verification.
 *
 * @dev Statement public-input ordering (for r4-threshold-count-v1):
 *      [0] bundle_root
 *      [1] period_start (unix seconds)
 *      [2] period_end
 *      [3] threshold
 *      [4] policy_id (Poseidon hash, field element)
 *      [5] amount_cap (cents)
 *      [6] issuer_pk_x
 *      [7] issuer_pk_y
 */
contract R4Groth16Verifier {

    // BN254 verifying key parameters — populated by ceremony output.
    // Production: auto-generated by snarkjs `verifier_groth16.sol.ejs`.
    struct VerifyingKey {
        uint256[2] alpha1;
        uint256[2][2] beta2;
        uint256[2][2] gamma2;
        uint256[2][2] delta2;
        uint256[2][] IC;
    }

    bytes32 public immutable vkHash;
    address public immutable circuitRegistry;

    event ProofVerified(
        bytes32 indexed circuitId,
        bytes32 indexed bundleRoot,
        address indexed verifier,
        uint256[8] publicInputs
    );

    constructor(bytes32 _vkHash, address _circuitRegistry) {
        vkHash = _vkHash;
        circuitRegistry = _circuitRegistry;
    }

    /**
     * @notice Verify an R+4 proof and emit an event.
     * @param a Groth16 proof component pi_a
     * @param b Groth16 proof component pi_b
     * @param c Groth16 proof component pi_c
     * @param publicInputs The 8 public field elements for the circuit
     * @return ok True iff the SNARK verifies
     */
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[8] calldata publicInputs
    ) external returns (bool ok) {
        // Production: call into snarkjs-generated pairing check using
        // the bn256 precompile (addresses 0x06, 0x07, 0x08).
        // This sketch returns true unconditionally — replace with the
        // generated pairing-check before production deployment.
        ok = _pairingCheck(a, b, c, publicInputs);

        if (ok) {
            emit ProofVerified(
                bytes32(uint256(uint160(address(this)))),
                bytes32(publicInputs[0]),
                msg.sender,
                publicInputs
            );
        }
    }

    /**
     * @notice Convenience entrypoint that takes a packed bytes blob.
     */
    function verifyProofBytes(bytes calldata proof, uint256[8] calldata publicInputs)
        external
        returns (bool)
    {
        require(proof.length == 256, "R+4: invalid proof length");
        uint256[2] memory a;
        uint256[2][2] memory b;
        uint256[2] memory c;
        (a, b, c) = _decodeProof(proof);
        return this.verifyProof(a, b, c, publicInputs);
    }

    function _decodeProof(bytes calldata proof)
        internal
        pure
        returns (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c)
    {
        // 256 bytes = 8 × uint256 = pi_a(2) + pi_b(4) + pi_c(2)
        assembly {
            calldatacopy(a, proof.offset, 64)
            calldatacopy(b, add(proof.offset, 64), 128)
            calldatacopy(c, add(proof.offset, 192), 64)
        }
    }

    function _pairingCheck(
        uint256[2] calldata, // a
        uint256[2][2] calldata, // b
        uint256[2] calldata, // c
        uint256[8] calldata // publicInputs
    ) internal pure returns (bool) {
        // SKETCH ONLY — production version is the snarkjs-generated check.
        return true;
    }
}
